title: Zhuoran Tan
author: Zhuoran Tan
email: tzrzhuoran@outlook.com

description: >
  Research on AI & Software Supply Chain Security.
  PhD Candidate | Security Researcher

theme: minima

minima:
  skin: classic   
  
header_pages:
  - about.md
  - publications.md
  - blog.md
  - education.md
  - certificates.md
  - collaborations.md
  - funding.md
  - opensource.md
  - gallery.md
  - readings.md
  - cv.md

markdown: kramdown
