title: Zhuoran Tan
author: Zhuoran Tan
email: tzrzhuoran@outlook.com

description: >
  Research on Software & AI Supply Chain Security.
  PhD Candidate | Security Researcher

theme: minima

minima:
  skin: classic   
  
header_pages:
  - about.md
  - publications.md
  - blog.md
  - collaborations.md
  - funding.md
  - opensource.md
  - gallery.md
  - reading.md
  # - cv.md

markdown: kramdown
